---
title: "Homework 3 Solutions"
date: "Due 10/??/2019"
output: html_document
editor_options: 
  chunk_output_type: inline
---

In this homework assignment, you will use the Gapminder dataset to build a Shiny app with two tabs. Otherwise, the layout of your Shiny app does not matter, as long as your final product is easy to navigate and interpret. Some inspiration can be found [here](https://shiny.rstudio.com/articles/layout-guide.html) or by browsing the [Shiny gallery](https://shiny.rstudio.com/gallery/). 

**Submission instructions for uploading Shiny app; also need to turn in an .Rmd file for their written answers?**

The [Gapminder Foundation](https://www.gapminder.org/) is an organization dedicated to educating the public by using data to dispel misconceptions about global development. You can load the dataset from the `dslabs` package. The `gapminder` data frame contains health and income outcomes for 184 countries from 1960 to 2016, with the variables listed below. We will focus on life expectancy as our outcome of interest. For the purpose of this assignment, don't worry about handling missing values and ignore all messages informing you that rows with missing values have been removed. 

- country.
- year.
- infant_mortality. Infant deaths per 1000.
- life_expectancy. Life expectancy in years.
- fertility. Average number of children per woman.
- population. Country population.
- gpd. GDP according to World Bankdev.
- continent.
- region. Geographical region.

```{r}
library(dslabs)
data(gapminder)
```

1. Create a Shiny app with a line plot of life expectancy against year, restricted to observations from the United States. How has life expectancy in the United States changed over time? 

**Solution:** 
Life expectancy in the United States appears to have increased at a fairly constant rate between 1960 and 2016. 

2. It might be interesting to compare life expectancy over time in the United States with trends in other countries. Use the `selectInput` function to create a select list input widget that allows you to select another country. Update your time series plot so that it now has two lines: one that plots life expectancy in the United States against year, and one that plots life expectancy in the selected country against year. 

**Solution:** N/A

3. Compare life expectancy over time in the United States with life expectancy over time in Switzerland. Then compare the United States and Swaziland (renamed Eswatini in 2018, but referred to as Swaziland in the `gapminder` dataset). 

**Solution:** 
Life expectancy in the United States has consistently remained below that in Switzerland for any given year. Overall, life expectancy in the two countries have roughly parallel trajectories, with perhaps some divergence in recent decades. 

On the other hand, life expectancy in the United States is consistently higher than that in Eswatini for any given year. Moreover, there is also a huge dip in life expectancy in Eswatini (the lowest point being in the mid-2000s) that is likely attributable to the AIDS epidemic in sub-Saharan Africa  [[source](https://www.unaids.org/en/regionscountries/countries/swaziland)]. 

4. Use `tabsetPanel` and `tabPanel` to make two tabs for your Shiny app. Move your time series plot and country selector widget from Questions 1-3 to the first tab. 

**Solution:** N/A

5. In the second tab, make a scatterplot of life expectancy against fertility rate, filtering for the year 2000 and coloring by continent. What trends do you see? 

**Solution:** 
In general, it appears that high life expectancy is associated with lower fertility rates. One could argue that countries from the same continent cluster loosely together. While many of the countries with high life expectancies and low fertility rates are European and many of the countries with low life expectancies and high fertility rates are African, there are exceptions. 

6. Still in the second tab, use `sliderInput` to add a slider widget that allows the user to select year. Update your scatterplot so that it plots life expectancy against fertility rate for the selected year. Optional: experiment with the arguments of `sliderInput` to make your widget look nice (e.g., get rid of the comma, make sure that the years are always integers, etc.). 

**Solution:** N/A

7. Make your scatterplot interactive by allowing the user to click on a point to get more information about the observation. You can do this by including calls to `plotOutput` in the UI and `nearPoints` in the server; a demo is available [here](https://shiny.rstudio.com/gallery/plot-interaction-selecting-points.html). When the user clicks somewhere on the plot, your app should print a data frame with the corresponding life expectancy, fertility, country, and continent for all points near the click. 

**Solution:** N/A

8. Look at your scatterplot of life expectancy against fertility rate with the year selected as 1980. Do you see a major outlier? Does the outlier have an unusual value for life expectancy and fertility, or for only one of the variables? Click on this point to get more information. What country is the outlier? 

**Solution:** 
Cambodia is the most obvious outlier. In 1980, it was recorded as having an incredibly low life expectancy of 28.16. Its fertility rate of 5.69 was much less unusual (many other countries had fertility rates of 7+). 

9. How has life expectancy changed over time for the outlier country from Question 8? You can use your time series plot in the first tab to answer this question. 

**Solution:** 
Life expectancy in Cambodia has an upward trend with the exception of a sharp drop from around 1970 to the mid-80s. The Cambodian genocide under the rule of the Khmer Rouge (1975-1979) falls right in the middle of that [[source](https://www.bbc.com/news/world-asia-pacific-10684399)].  

10. Suggest another interactive feature that you could incorporate into your Shiny app, perhaps involving one (or more) of the other variables in the `gapminder` dataset. What `R/shiny` function(s) would you use to implement this feature? Optional: add the feature to your Shiny app, as long as it doesn't interfere with the functionality of the non-optional parts of this assignment. 

**Solution:** 
Any reasonable answer that names the appropriate `R/shiny` function to implement the described feature will be accepted. 
