---
title: "Homework 3"
date: "Due 11/1/2019"
output: html_document
editor_options: 
  chunk_output_type: inline
---

In this homework assignment, you will use the Gapminder dataset to build a Shiny app with two tabs. Otherwise, the layout of your Shiny app does not matter, as long as your final product is easy to navigate and interpret. Some inspiration can be found [here](https://shiny.rstudio.com/articles/layout-guide.html) or by browsing the [Shiny gallery](https://shiny.rstudio.com/gallery/). 

Note that for this assignment you will need to push 3 files to your HW3 repository:

1. **HW3.Rmd** with all of your written answers to questions 1, 3, 5, 8, 9 and 10.
2. **HW3.html**, the knitted HW3.Rmd file
3. **app.R** file for your Shiny app

Also note that both the .Rmd file and Shiny app file need to run on our computers as well as yours.


The [Gapminder Foundation](https://www.gapminder.org/) is an organization dedicated to educating the public by using data to dispel misconceptions about global development. You can load the dataset from the `dslabs` package. The `gapminder` data frame contains health and income outcomes for 184 countries from 1960 to 2016, with the variables listed below. We will focus on life expectancy as our outcome of interest. **For the purpose of this assignment, don't worry about handling missing values and ignore all messages informing you that rows with missing values have been removed**. 

- `country`
- `year`
- `infant_mortality`: Infant deaths per 1000.
- `life_expectancy`: Life expectancy in years.
- `fertility`: Average number of children per woman.
- `population`: Country population.
- `gdp`: GDP according to World Bankdev. in US dollars
- `continent`
- `region`: Geographical region.

```{r}
library(dslabs)
data(gapminder)
```

1. Create a Shiny app with a line plot of life expectancy against year, restricted to observations from the United States. How has life expectancy in the United States changed over time? 

*Your answer here*

2. It might be interesting to compare life expectancy over time in the United States with trends in other countries. Use the `selectInput` function to create a select list input widget that allows you to select another country. Update your time series plot so that it now has two lines: one that plots life expectancy in the United States against year, and one that plots life expectancy in the selected country against year. 

*No written answer needed*

3. Compare life expectancy over time in the United States with life expectancy over time in Switzerland. Then compare the United States and Swaziland (renamed Eswatini in 2018, but referred to as Swaziland in the `gapminder` dataset). 

*Your answer here*

4. Use `tabsetPanel` and `tabPanel` to make two tabs for your Shiny app. Move your time series plot and country selector widget from Questions 1-3 to the first tab. 

*No written answer needed*

5. In the second tab, make a scatterplot of life expectancy against fertility rate, filtering for the year 2000 and coloring by continent. What trends do you see? 

*Your answer here*

6. Still in the second tab, use `sliderInput` to add a slider widget that allows the user to select year. Update your scatterplot so that it plots life expectancy against fertility rate for the selected year. Optional: experiment with the arguments of `sliderInput` to make your widget look nice (e.g., get rid of the comma, make sure that the years are always integers, etc.). 

*No written answer needed*

7. Make your scatterplot interactive by allowing the user to click on a point to get more information about the observation. You can do this by including calls to `plotOutput` in the UI and `nearPoints` in the server; a demo is available [here](https://shiny.rstudio.com/gallery/plot-interaction-selecting-points.html). When the user clicks somewhere on the plot, your app should print a data frame with the corresponding life expectancy, fertility, country, and continent for all points near the click. 

*No written answer needed*

8. Look at your scatterplot of life expectancy against fertility rate with the year selected as 1980. Do you see a major outlier? Does the outlier have an unusual value for life expectancy and fertility, or for only one of the variables? Click on this point to get more information. What country is the outlier? 

*Your answer here*

9. How has life expectancy changed over time for the outlier country from Question 8? You can use your time series plot in the first tab to answer this question. 

*Your answer here*

10. Suggest another interactive feature that you could incorporate into your Shiny app, perhaps involving one (or more) of the other variables in the `gapminder` dataset. What `R/shiny` function(s) would you use to implement this feature? Optional: add the feature to your Shiny app, as long as it doesn't interfere with the functionality of the non-optional parts of this assignment. 

*Your answer here*
