---
title: "Midterm Review 2019"
output: html_document
---
### Format
* The midterm will be in class on Wednesday, October 16th from 9:45-11:15am.


* Exam will be through Canvas.


* There will be 11 or 12 questions. If you answer 10 questions correctly, you will receive 100%. If you answer more than 10 questions correctly, you will also receive extra credit. 


* Each question will be multiple choice, but you will have to write and run code on your laptop in order to answer some questions. You are graded soley on the answer you choose, not the code you write to get the answer.


* The use of cell phones is **NOT** permitted during the exam.


* You may use lecture notes, homework solutions and the internet during the exam. However, we will be walking around to make sure nobody is messaging each other on Slack, gchat, or any other kind of instant message platform. This is an individual exam and communication with other students is **NOT** permitted.


* If you have a question during the exam, raise your hand and a TA or the instructor will walk over to you. **DO NOT ask questions on Slack.**


* **Please charge your laptop before the exam** so you don't have to sit on the floor by an outlet.

* All material presented in class before the midterm (September 4th - October 9th) is fair game.

### Major topics included (not an exhaustive list)

* Loading data into R
* Basic Data Wrangling
* Basic Plots
* Plotting with `ggplot2`
* Visualization principles


### Major functions to review (not an exhaustive list)

* `read.csv()`
* `head()`
* `top_n()`
* `group_by()`
* `summarize()`
* `filter()`
* `mutate()`
* `arrange()`
* `%>%`
* `function(){}`
* `ggplot()`; refer to [cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf)
* `seq()`
* `c()`
* `data.frame()`
* `which()`
* `which.max()`
* `which.min()`
* `is.na()`
* `print()`
* `for()`
* `ifelse()`
* `mean()`
* `sd()`
* `sqrt()`
* `sum()`
* Reviewing homework assignments, reading the lecture files, and coding the examples on your own are the best ways to prepare.

### Major packages to load (not an exhaustive list)

* `dslabs`
* `dplyr`
* `ggplot2`
* `ggthemes`
* `ggrepel`
* `RColorBrewer`
